# Generated by Django 4.0.1 on 2022-02-18 18:57

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('hotelID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotelname', models.CharField(max_length=60)),
                ('zipCode', models.IntegerField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('hotel_location', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=api.models.profile.namefile),
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Rooms_info',
            fields=[
                ('room_number', models.IntegerField(default=uuid.UUID('ba32f4ce-38a9-42d1-bbfa-4cbb8345959d'), editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=60)),
                ('room_price', models.FloatField(max_length=200)),
                ('number_of_beds', models.IntegerField(max_length=60)),
                ('hotelID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hotels')),
            ],
        ),
    ]
