# Generated by Django 4.0.1 on 2022-02-18 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hotels_alter_profile_picture_alter_signup_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='zipCode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms_info',
            name='number_of_beds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rooms_info',
            name='room_number',
            field=models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
