# Generated by Django 4.0.1 on 2022-02-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_hotels_zipcode_alter_rooms_info_number_of_beds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='hotelname',
            new_name='hotelName',
        ),
    ]
