# Generated by Django 4.0.1 on 2022-02-18 19:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_hotelname_hotels_hotelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms_info',
            name='roomImage',
            field=models.ImageField(blank=True, upload_to=api.models.Rooms_info.namefile),
        ),
    ]
