# Generated by Django 4.0.1 on 2022-02-18 20:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_rooms_info_hotelid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms_info',
            name='hotelID',
            field=models.ForeignKey(default=uuid.UUID('2f67df81-da25-4edb-ae64-35432340ab8a'), null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hotels'),
        ),
        migrations.AlterField(
            model_name='rooms_info',
            name='room_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
