# Generated by Django 4.0.1 on 2022-02-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rooms_info_hotelid_alter_rooms_info_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms_info',
            name='hotelID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hotels'),
        ),
    ]
