# Generated by Django 4.0.1 on 2022-02-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rooms_info_hotelid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='State',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotelID',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rooms_info',
            name='room_number',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
