# Generated by Django 4.0.1 on 2022-04-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_state_hotels_state_alter_hotels_hotelid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('PhoneNumber', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('customer_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('phoneNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer_details')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                 ('customerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer_details')),
                ('reservationNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationNumber', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('checkInDateTime', models.DateField()),
                ('checkOutDateTime', models.DateField()),
                ('reservationGuest', models.CharField(max_length=30)),
                ('numberOfGuest', models.IntegerField()),
                ('CustomerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer_info')),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('serviceId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=30)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='service_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qunatity', models.IntegerField(editable=False)),
                ('totalServicePrice', models.FloatField()),
                ('hotelId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hotels')),
                ('reservationNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
                ('serviceId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.services')),
            ],
            options={
                'unique_together': {('serviceId', 'hotelId', 'reservationNumber')},
            },
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hotels')),
                ('reservationNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
                ('roomNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rooms_info')),
            ],
            options={
                'unique_together': {('roomNumber', 'hotelId', 'reservationNumber')},
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer_info')),
                ('reservationNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
            ],
            options={
                'unique_together': {('customerId', 'reservationNumber')},
            },
        ),
        migrations.CreateModel(
            name='billingInfo',
            fields=[
                ('billingId', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('totalBilling', models.FloatField()),
                ('paymentDate', models.DateField()),
                ('reservationNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reservation')),
            ],
            options={
                'unique_together': {('billingId', 'reservationNumber')},
            },
        ),
    ]
