# Generated by Django 4.0.1 on 2022-04-02 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_customer_details_customer_info_reservation_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_info',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer_details',
            name='PhoneNumber',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
