# Generated by Django 4.0.1 on 2022-04-05 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_user_alter_customer_info_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_info',
            name='userid',
        ),
        migrations.AddField(
            model_name='customer_info',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
