# Generated by Django 4.0.1 on 2022-04-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_adminuser_customeruser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminUser',
        ),
        migrations.DeleteModel(
            name='customeruser',
        ),
    ]
