# Generated by Django 4.0.1 on 2022-04-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_adminuser_customeruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminUser',
        ),
        migrations.DeleteModel(
            name='customeruser',
        ),
    ]
