# Generated by Django 4.0.1 on 2022-04-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_delete_adminuser_delete_customeruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_info',
            old_name='phoneNumber',
            new_name='phoneNumber_id',
        ),
    ]
