# Generated by Django 4.0.1 on 2022-04-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_phonenumber_customer_info_phonenumber_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_details',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='customer_details',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
