# Generated by Django 4.0.1 on 2022-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_customer_details_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_info',
            old_name='phoneNumber_id',
            new_name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='customer_details',
            name='id',
        ),
        migrations.AddField(
            model_name='customer_details',
            name='PhoneNumber',
            field=models.CharField(default=1, max_length=60, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
