# Generated by Django 4.0.1 on 2022-04-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_phonenumber_id_customer_info_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_info',
            old_name='phoneNumber',
            new_name='phoneNumber_id',
        ),
    ]
