# Generated by Django 4.0.1 on 2022-04-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_phonenumber_customer_info_phonenumber_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_info',
            old_name='phoneNumber_id',
            new_name='phoneNumber_i',
        ),
    ]
