# Generated by Django 4.0.1 on 2022-04-16 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_phonenumber_id_customer_info_phonenumber_i'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_info',
            old_name='phoneNumber_i',
            new_name='phoneNumber',
        ),
    ]
