# Generated by Django 4.0.1 on 2022-04-16 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_phonenumber_i_customer_info_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='phoneNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.customer_details'),
        ),
    ]
