# Generated by Django 4.0.1 on 2022-04-16 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_customer_info_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_info',
            old_name='customer_id',
            new_name='customerId',
        ),
    ]
