# Generated by Django 4.0.1 on 2022-04-16 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_customerid_customer_info_customerid_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customer',
            name='customerId_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.customer_info'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reservationNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.reservation'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('customerId_id', 'reservationNumber')},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customerId',
        ),
    ]
