# Generated by Django 4.0.1 on 2022-04-16 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_customer_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customerId',
        ),
        migrations.AddField(
            model_name='customer',
            name='customerId_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.customer_info'),
        ),
    ]
