# Generated by Django 4.0.1 on 2022-04-16 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_customer_customerid_customer_customerid_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customerId_id',
            new_name='customerId',
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('customerId', 'reservationNumber')},
        ),
    ]
