# Generated by Django 4.0.1 on 2022-04-16 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_customerid_id_customer_customerid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('customerId',)},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='reservationNumber',
        ),
    ]
